### ISSUE TITLE
ERROR: 중복회원 검사 테스트 코드 작성 중 DataIntegrityViolationException 에러 발생

### ISSUE THREAD

**Issue by baexxbin** [baexxbin/Inknow-BE#1]
### 📌 문제 정의
중복회원 검사 테스트 코드 작성 중 예상치 못한 DataIntegrityViolationException 에러 발생

### 🔎 문제 상황
```
@Test(expected = IllegalStateException.class)
    public void 중복_회원_예외() throws Exception {
        //Given
        Member member1 = new Member();
        member1.setHiddenName("bae");

        Member member2 = new Member();
        member2.setHiddenName("bae");

        //When
        memberService.join(member1);
        memberService.join(member2);

        //Then
        fail("예외가 발생해야함");
    }
```
<br>

> * ⚠️ 에러 메세지 내용
>
> `java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<org.springframework.dao.DataIntegrityViolationException>`

join 과정에서 에러발생

**Comment by baexxbin** [comment]
* 예외 설명
DataIntegrityViolationException은 일반적으로 데이터베이스 제약 조건 위반이나, 기타 데이터베이스 관련 예외가 발생할 때 발생하는 예외.

* 예외 발생 이유
현재 특별한 설정을 해주지 않은 hiddenName에서 제약조건이 걸려 데이터베이스 무결성을 위반했다고 함.

* 의심되는 부분
현재 필드이름인 hiddenName은 mysql에서 hiddenname칼럼으로 매핑되고 해당 칼럼이 자동생성될 시 제약조건이 걸렸을 수 있다.

* 🛠️ 의심부분 수정
**안전한 매핑을 위해 @Column(name = "hidden_name")추가**

* 오류 해결 여부
❌ 오류해결 안됨

**Comment by desfox** [comment]
member1이나 member2 객체를 저장할 때 이미 DB에 있는 값이랑 충돌했을 수도 있을 것 같은데 일단은 아래처럼 
memberService.join()에서 Repository에 저장하는 코드를 try-catch로 묶어서 IllegalArgumentException을 던지게 하거나 e.printstacktrace()나 e.getMessage()로 메세지를 출력해보세요

`
try {
			memberRepository.save(member);
		} catch (DataIntegrityViolationException e) {
			throw new IllegalArgumentException("message");
		}
`

**Comment by baexxbin** [comment]
> 

디버그를 돌렸을 때 save전에 실행되는 validateDuplicateMember매소드의 memberRepository.findByHiddenName(member.getHiddenName()); 에서 오류가 터집니다.. 

findByHiddenName()매소드가 수상합니다...!

**Comment by desfox** [comment]
코드를 보니 쿼리문을 날렸을 때 DB 무결성을 어겨서 발생한 에러 같습니다.

기존 DB의 데이터와 중복이 되었거나, 예상치 못한 제약조건이 걸려있어서 그럴 수도 있으니 Member 테이블과 제약조건 테이블을 조회한 뒤, 문제가 될만한 데이터를 삭제하면 해결할 수도 있을 것 같네요.

해당 글을 참고하시면 도움될 것 같습니다!
[https://thisisprogrammingworld.tistory.com/167?category=954971](https://thisisprogrammingworld.tistory.com/167?category=954971)

**Comment by baexxbin** [comment]
### 🎉 이슈 해결

* 오류 원인 
Member의 poin변수(컬럼)의 int자료형

int는 null값을 가질 수 없는 원시 자료형으로 해당 컬럼이 null값을 가지려고 해서 오류가 발생 함.
회원가입 진행 시 point값을 설정하지 않았으므로 null값이 들어감. 

* 해결 방법
int형인 point와 scrapLimit의 타입을 Integer로 변경.

앞서 회원가입 테스트는 정상적으로 동작했는데, 회원중복테스트에서 오류가 발생했다. 이는 db에서 hiddenName으로 중복회원을 확인하는 과정에서 멤버를 조회하고, 멤버의 변수들을 조회하는 과정에서 point 값이 null로 설정되어 발생한 것이라고 추측된다.
